version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Shitting hell!"
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "testicles"
      - run: sleep 5
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
        # only run if build success
        requires:
          - build
